# Generated by Django 2.2.5 on 2019-10-05 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0002_address_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='updated',
            field=models.DateTimeField(),
        ),
        migrations.AlterModelTable(
            name='profile',
            table='profile',
        ),
    ]
