# Generated by Django 2.2.5 on 2019-10-05 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0003_auto_20191005_0234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='picture',
        ),
        migrations.AddField(
            model_name='address',
            name='ip_address',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterModelTable(
            name='profile',
            table=None,
        ),
    ]
