# Generated by Django 2.2.5 on 2019-10-05 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0004_auto_20191005_0352'),
    ]

    operations = [
        migrations.CreateModel(
            name='fund',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=20)),
                ('can_remite', models.CharField(max_length=20)),
                ('balance', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='address',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
