# Generated by Django 2.2.6 on 2019-10-06 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0005_auto_20191005_1035'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=20)),
                ('rcode', models.CharField(max_length=20)),
                ('rtime', models.CharField(max_length=20)),
                ('rdate', models.CharField(max_length=20)),
                ('n', models.CharField(default=1, max_length=20)),
                ('as_viewed', models.BooleanField(default=False)),
            ],
        ),
    ]
