# Generated by Django 2.2.6 on 2019-10-06 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0006_requestdetail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requestdetail',
            old_name='as_viewed',
            new_name='as_accepted',
        ),
    ]
