# Generated by Django 2.2.6 on 2019-10-06 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0007_auto_20191006_2335'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requestdetail',
            old_name='as_accepted',
            new_name='has_accepted',
        ),
    ]
