# Generated by Django 2.2.6 on 2019-10-07 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0008_auto_20191006_2337'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestdetail',
            name='send',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='requestdetail',
            name='url',
            field=models.URLField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
