# Generated by Django 2.2.6 on 2019-10-07 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0010_sentfunc'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentfunc',
            name='rcode',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
