# Generated by Django 2.2.6 on 2019-10-07 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0011_sentfunc_rcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentfunc',
            name='check',
            field=models.BooleanField(default=False),
        ),
    ]
