# Generated by Django 2.2.6 on 2019-10-07 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0012_sentfunc_check'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestdetail',
            name='update',
            field=models.BooleanField(default=False),
        ),
    ]
