# Generated by Django 2.2.6 on 2019-10-07 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0014_requestdetail_added'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestdetail',
            name='added',
        ),
    ]
