# Generated by Django 2.2.6 on 2019-10-07 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0015_remove_requestdetail_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestdetail',
            name='has_declined',
            field=models.BooleanField(default=False),
        ),
    ]
