# Generated by Django 2.2.6 on 2019-10-07 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0016_requestdetail_has_declined'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestdetail',
            name='customer',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
