# Generated by Django 2.2.6 on 2019-10-07 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0018_requestdetail_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestdetail',
            name='amount',
        ),
    ]
