# Generated by Django 2.2.6 on 2019-10-08 10:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0020_requestdetail_amount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'ordering': ['-created']},
        ),
        migrations.AlterModelOptions(
            name='fund',
            options={'ordering': ['-created']},
        ),
        migrations.AlterModelOptions(
            name='isagent',
            options={'ordering': ['-created']},
        ),
        migrations.AlterModelOptions(
            name='requestdetail',
            options={'ordering': ['-created']},
        ),
        migrations.AlterModelOptions(
            name='sentfunc',
            options={'ordering': ['-created']},
        ),
        migrations.RenameField(
            model_name='sentfunc',
            old_name='time',
            new_name='created',
        ),
        migrations.AddField(
            model_name='address',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fund',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='isagent',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='requestdetail',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
