# Generated by Django 2.2.6 on 2019-10-08 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0021_auto_20191008_1136'),
    ]

    operations = [
        migrations.CreateModel(
            name='visited',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rcode', models.CharField(max_length=20)),
                ('visit', models.CharField(default=0, max_length=2)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
