# Generated by Django 2.2.6 on 2019-10-08 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0023_rcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestdetail',
            name='rdate',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='requestdetail',
            name='rtime',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='requestdetail',
            name='url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
