# Generated by Django 2.2.6 on 2019-10-11 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0024_auto_20191008_1858'),
    ]

    operations = [
        migrations.CreateModel(
            name='rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=20)),
                ('accept', models.CharField(max_length=20)),
                ('declined', models.CharField(max_length=20)),
                ('expired', models.CharField(max_length=20)),
                ('total', models.CharField(max_length=20)),
                ('average_rating', models.CharField(max_length=20)),
                ('average_accept', models.CharField(max_length=20)),
                ('average_declined', models.CharField(max_length=20)),
                ('average_expired', models.CharField(max_length=20)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
