# Generated by Django 2.2.6 on 2019-10-11 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0025_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='qr_code',
            field=models.ImageField(default='media/default/codes.jpg', upload_to='profile/qrcode'),
        ),
    ]
