# Generated by Django 2.2.6 on 2019-10-11 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0026_auto_20191011_0605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='qr_code',
            field=models.ImageField(default='media/default/codes.jpg', upload_to='media/profile/qrcode'),
        ),
    ]
