# Generated by Django 2.2.6 on 2019-10-11 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0027_auto_20191011_2340'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileAvatar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=29)),
                ('image', models.ImageField(upload_to='media/default/')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
