# Generated by Django 2.2.6 on 2019-10-12 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0028_profileavatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='picture',
            field=models.ImageField(default=1, upload_to='profile/picture'),
            preserve_default=False,
        ),
    ]
