# Generated by Django 2.2.6 on 2019-10-12 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0029_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfilePic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=20)),
                ('picture', models.ImageField(upload_to='profile/picture')),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='picture',
        ),
    ]
