# Generated by Django 2.2.6 on 2019-10-12 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0031_auto_20191012_0252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='qr_code',
            field=models.ImageField(default='default/codes.jpg', upload_to='profile/qrcode'),
        ),
    ]
