# Generated by Django 2.2.6 on 2019-10-15 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0033_isverified'),
    ]

    operations = [
        migrations.AddField(
            model_name='isverified',
            name='opt',
            field=models.BooleanField(default=False),
        ),
    ]
