# Generated by Django 2.2.6 on 2019-10-15 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0034_isverified_opt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='isverified',
            old_name='opt',
            new_name='otp',
        ),
    ]
