# Generated by Django 2.2.6 on 2019-10-15 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0035_auto_20191015_2218'),
    ]

    operations = [
        migrations.AddField(
            model_name='isverified',
            name='telephone',
            field=models.CharField(default=1, max_length=13),
            preserve_default=False,
        ),
    ]
