# Generated by Django 2.2.6 on 2019-10-15 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0036_isverified_telephone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='isverified',
            name='otp',
            field=models.CharField(max_length=6),
        ),
    ]
