# Generated by Django 2.2.6 on 2019-10-18 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0037_auto_20191015_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rcode',
            name='rcode',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='requestdetail',
            name='rcode',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='sentfunc',
            name='rcode',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='visited',
            name='rcode',
            field=models.CharField(max_length=100),
        ),
    ]
