# Generated by Django 2.2.6 on 2019-10-21 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0038_auto_20191018_0730'),
    ]

    operations = [
        migrations.CreateModel(
            name='InAcct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=20)),
                ('rcode', models.CharField(max_length=100)),
                ('pattern', models.CharField(max_length=100)),
                ('balance', models.CharField(max_length=15)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
