# Generated by Django 2.2.6 on 2019-10-21 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0039_inacct'),
    ]

    operations = [
        migrations.AddField(
            model_name='inacct',
            name='xtrafund',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
    ]
