# Generated by Django 2.2.6 on 2019-10-22 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0040_inacct_xtrafund'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fund',
            name='balance',
            field=models.PositiveIntegerField(max_length=20),
        ),
        migrations.AlterField(
            model_name='fund',
            name='can_remite',
            field=models.PositiveIntegerField(max_length=20),
        ),
    ]
