# Generated by Django 2.2.6 on 2019-10-22 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0041_auto_20191022_0303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fund',
            name='balance',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='fund',
            name='can_remite',
            field=models.PositiveIntegerField(),
        ),
    ]
