# Generated by Django 2.2.6 on 2020-02-04 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0042_auto_20191022_0303'),
    ]

    operations = [
        migrations.CreateModel(
            name='Veri',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=20)),
                ('rcode', models.CharField(max_length=100)),
                ('count', models.CharField(default=1, max_length=2)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
