# Generated by Django 2.2.6 on 2019-10-18 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PatternKey',
            new_name='Checkout',
        ),
    ]
