# Generated by Django 2.2.6 on 2020-01-25 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=20)),
                ('trans_id', models.CharField(max_length=20)),
                ('amount', models.CharField(max_length=20)),
                ('agent', models.CharField(max_length=20)),
                ('status', models.BooleanField(default=False)),
                ('time', models.CharField(max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
