# Generated by Django 2.2.6 on 2020-01-25 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='agent',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='history',
            name='amount',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='history',
            name='time',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='history',
            name='trans_id',
            field=models.CharField(max_length=250),
        ),
    ]
