# Generated by Django 2.2.6 on 2020-01-26 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0003_activity'),
    ]

    operations = [
        migrations.CreateModel(
            name='design',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=20)),
                ('background', models.BooleanField(default=False)),
                ('color', models.CharField(max_length=50)),
                ('img', models.CharField(max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
